export const GET_SINGLE_PRODUCT_DETAILS = "GET_SINGLE_PRODUCT_DETAILS";
export const GET_PRODUCT_LIST_MAIN = "GET_PRODUCT_LIST_MAIN";
export const TOGGLE_PRODUCT_MODAL = "TOGGLE_PRODUCT_MODAL";
export const GET_FLASH_DEAL_DATA = "GET_FLASH_DEAL_DATA";
export const GET_MODAL_DATA= "GET_MODAL_DATA";
export const GET_SEARCHED_PRODUCT_LIST= "GET_SEARCHED_PRODUCT_LIST";