export const GET_USER_STORAGE_DATA = "GET_USER_STORAGE_DATA";
export const LOGOUT_USER = "LOGOUT_USER";
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
export const SET_WEBSITE_INFO_LOADING = 'SET_WEBSITE_INFO_LOADING';
export const SET_WEBSITE_INFO = 'SET_WEBSITE_INFO';
export const POST_SUBSCRIBE_NEWSLETTER = 'POST_SUBSCRIBE_NEWSLETTER';